name: 'My Custom Action'
description: 'An action that echoes the example_input parameter'
inputs:
  example_input:
    description: 'The input to be echoed'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Echo example_input
      shell: bash
      run: |
        echo "This dev branch"
        echo "${{ inputs.example_input }}"
