name: Dynamic Action Version

on:
  workflow_dispatch:
    inputs:
      action_version:
        description: "Action Version (e.g., v1, v2, main ,dev)"
        required: true
        default: "dev"

jobs:
  dynamic-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - uses: lsjczh/BaseWorkflow/.github/actions/dynamic-uses@main
        with:
          uses: lsjczh/BaseWorkflow/.github/actions/my-action@${{ github.event.inputs.action_version }}
          with: '{ "example_input": 18 }'
