name: Dynamic Action Version

on:
  workflow_dispatch:
    inputs:
      action_version:
        description: "Action Version (e.g., v1, v2, main)"
        required: true
        default: "v1"

jobs:
  dynamic-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Action Version
        id: version
        run: echo "VERSION=${{ github.event.inputs.action_version }}" >> $GITHUB_ENV  # 将版本号存入环境变量

      - name: Run Dynamic Action
        uses: my-org/my-action@${{ env.VERSION }}  # 动态指定 Action 版本
