# BaseWorkflow 仓库中的 .github/workflows/main-workflow.yml
name: Base Reusable Workflow
on:
  workflow_dispatch:
    inputs:
      example_input:
        description: 'Input for example action'
        required: true
        type: string
jobs:
  run-my-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run custom action from BaseWorkflow
        # 这里的相对路径引用 BaseWorkflow 仓库中的 action 文件
        uses: ./.github/actions/my-action
        with:
          some_parameter: ${{ inputs.example_input }}
