# BaseWorkflow 仓库中的 .github/workflows/main-workflow.yml
name: Base Reusable Workflow
on:
  workflow_dispatch:
    inputs:
      example_input:
        description: 'Input for example action'
        required: true
        type: string
  workflow_call:
    inputs:
      example_input:
        required: true
        type: string
jobs:
  run-my-action:
    runs-on: ubuntu-latest
    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#        with:
#          repository: lsjczh/BaseWorkflow
#      - name: Run custom action from BaseWorkflow 
#        uses: lsjczh/BaseWorkflow/.github/actions/my-action@${{ matrix.version }}
#        with:
#          example_input : ${{ inputs.example_input }}
      - name: Run Action dynamically
        run: |
          ACTION_VERSION=${{ github.event.inputs.example_input }}
          echo "Using Action version: $ACTION_VERSION"
          gh run lsjczh/BaseWorkflow/.github/actions/my-action@$ACTION_VERSION
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
