name: Main Workflow

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:   # 允许手动触发

jobs:
  run-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Run Action One
        uses: ./github/actions/action-one
        with:
          branch: ${{ github.ref_name }}

      - name: Run Action Two
        uses: ./github/actions/action-two
        with:
          branch: ${{ github.ref_name }}
