name: Start SS Server

on:
  workflow_dispatch:  # 允许手动触发

jobs:
  start-ss:
    runs-on: ubuntu-latest
    steps:
      - name: Install Shadowsocks
        run: |
          sudo apt update
          sudo apt install shadowsocks-libev -y

      - name: Configure SS Server
        run: |
          cat <<EOF | sudo tee /etc/shadowsocks-libev/config.json
          {
            "server":"0.0.0.0",
            "server_port":8388,
            "password":"your_password",
            "method":"aes-256-gcm",
            "fast_open": true,
            "mode": "tcp_and_udp"
          }
          EOF
          sudo systemctl restart shadowsocks-libev

      - name: Show Public IP
        run: curl -s ifconfig.me

      - name: Keep Running for 6 Hours
        run: sleep 21600  # 让任务持续 6 小时
